using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Concurrent;

static class UnusedUsingsCleanerHandler
{
    internal static async Task<int> CleanupAsync(
        Solution solution, StreamWriter resultWriter,
        ConcurrentDictionary<ProjectId, Compilation>? existingCompilations = null)
    {
        Console.WriteLine($"[INFO] Cleaning up unused using directives...");
        var sw = System.Diagnostics.Stopwatch.StartNew();

        var changes = new List<(string filePath, int count)>();
        int totalDocuments = 0;
        int totalRemoved = 0;
        int totalSkippedByVerify = 0;

        foreach (var projectId in solution.ProjectIds)
        {
            var project = solution.GetProject(projectId);
            if (project == null) continue;

            Compilation? compilation;
            if (existingCompilations != null && existingCompilations.TryGetValue(projectId, out var cached))
            {
				Console.WriteLine($"[INFO] Using cached compilations for projectId : {projectId}");
				compilation = cached;
            }
            else
            {
				Console.WriteLine($"[INFO] Calling GetCompilationAsync for projectId : {projectId}");
				compilation = await project.GetCompilationAsync();
            }

            if (compilation == null)
            {
				Console.WriteLine($"[INFO] Got no compilations for projectId : {projectId}");
				continue;
            }

            // Collect global usings from auto-generated sources (obj/ folder, *.g.cs).
            // MSBuildWorkspace may include these even when the real build doesn't generate them
            // (e.g., stale obj/ files, or implicit usings the project doesn't actually have).
            var suspectGlobalUsings = CollectAutoGeneratedGlobalUsings(compilation);

            // Get CS8019/CS0105 diagnostic spans (per-file error guard inside)
            var allUnusedUsingSpans = compilation.GetUnusedUsingSpans();

            foreach (var documentId in project.DocumentIds)
            {
                var document = project.GetDocument(documentId);
                if (document == null) continue;

                // Skip auto-generated files and ignored folders from appsettings
                var docPath = document.FilePath;
                if (string.IsNullOrEmpty(docPath) || IsGeneratedFile(docPath) || AnalysisHelpers.IsIgnoredPath(docPath))
                    continue;

                var root = await document.GetSyntaxRootAsync();
                if (root is not CompilationUnitSyntax compilationRoot) continue;

                var usings = compilationRoot.Usings;
                if (usings.Count == 0) continue;

                totalDocuments++;

                var unusedUsings = new List<UsingDirectiveSyntax>();

                foreach (var usingDirective in usings)
                {
                    // Skip using alias (using XXX = YYY)
                    if (usingDirective.Alias != null) continue;

                    // Skip static using
                    if (usingDirective.StaticKeyword.IsKind(SyntaxKind.StaticKeyword)) continue;

                    // Only remove if compiler flagged as CS8019 (unnecessary) or CS0105 (duplicate)
                    if (allUnusedUsingSpans.Contains(usingDirective.Span))
                    {
                        // Guard: skip if namespace overlaps with auto-generated global usings
                        // (the real build may not have these global usings)
                        var ns = usingDirective.Name?.ToString().Trim();
                        if (ns != null && suspectGlobalUsings.Contains(ns))
                            continue;

                        unusedUsings.Add(usingDirective);
                    }
                }

                if (unusedUsings.Count == 0) continue;

                var newRoot = compilationRoot.RemoveNodes(unusedUsings, SyntaxRemoveOptions.KeepNoTrivia);
                if (newRoot == null) continue;

                // Verification: ensure removal doesn't introduce compilation errors.
                // This catches cases where CS8019 is unreliable (incomplete references,
                // MSBuildWorkspace loading issues, etc.)
                var oldTree = compilation.SyntaxTrees.FirstOrDefault(t =>
                    string.Equals(t.FilePath, docPath, StringComparison.OrdinalIgnoreCase));

                if (oldTree != null)
                {
                    var newText = newRoot.ToFullString();
                    var newTree = CSharpSyntaxTree.ParseText(
                        newText,
                        (CSharpParseOptions?)oldTree.Options,
                        path: docPath);
                    var verifyCompilation = compilation.ReplaceSyntaxTree(oldTree, newTree);
                    var verifyDiags = verifyCompilation.GetSemanticModel(newTree).GetDiagnostics();

                    if (verifyDiags.Any(d => d.Severity == DiagnosticSeverity.Error))
                    {
                        totalSkippedByVerify++;
                        Console.WriteLine($"[WARN] Skipping {Path.GetFileName(docPath)} — removal would introduce errors");
                        continue;
                    }

                    // Verified safe — write the file
                    await System.IO.File.WriteAllTextAsync(docPath, newText);
                }
                else
                {
                    // Can't find matching tree in compilation — skip for safety
                    totalSkippedByVerify++;
                    Console.WriteLine($"[WARN] Skipping {Path.GetFileName(docPath)} — can't verify against compilation");
                    continue;
                }

                changes.Add((docPath, unusedUsings.Count));
                totalRemoved += unusedUsings.Count;

                var msg = $"[UNUSED-USING] Removed {unusedUsings.Count} unused using(s) from {Path.GetFileName(docPath)}";
                Console.WriteLine(msg);
                lock (resultWriter) resultWriter.WriteLine(msg);
            }
        }

        sw.Stop();
        var summary = $"[INFO] Scanned {totalDocuments} documents, removed {totalRemoved} unused usings from {changes.Count} files";
        if (totalSkippedByVerify > 0)
            summary += $", skipped {totalSkippedByVerify} files (verification)";
        summary += $" in {sw.Elapsed.TotalSeconds:F1}s";
        Console.WriteLine(summary);

        return totalRemoved;
    }

    /// <summary>
    /// Collects namespaces from global using directives in auto-generated files (obj/ folder, *.g.cs).
    /// These are "suspect" — MSBuildWorkspace may include them but the real dotnet build may not.
    /// Also includes CSharpCompilationOptions.Usings (programmatic global usings).
    /// </summary>
    private static HashSet<string> CollectAutoGeneratedGlobalUsings(Compilation compilation)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);

        // Programmatic global usings from compilation options
        if (compilation is CSharpCompilation csharpComp)
        {
            foreach (var u in csharpComp.Options.Usings)
                result.Add(u);
        }

        // Global using directives from auto-generated source files
        foreach (var tree in compilation.SyntaxTrees)
        {
            var treePath = tree.FilePath;
            if (string.IsNullOrEmpty(treePath) || !IsAutoGeneratedFile(treePath))
                continue;

            foreach (var u in tree.GetRoot().DescendantNodes().OfType<UsingDirectiveSyntax>())
            {
                if (u.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword) && u.Name != null)
                    result.Add(u.Name.ToString().Trim());
            }
        }

        if (result.Count > 0)
            Console.WriteLine($"[INFO] Found {result.Count} suspect global usings from auto-generated sources");

        return result;
    }

    /// <summary>
    /// Auto-generated files that may contain global usings not present in the real build.
    /// </summary>
    private static bool IsAutoGeneratedFile(string filePath)
    {
        var normalized = filePath.Replace('\\', '/');
        if (normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase))
            return true;
        var fileName = Path.GetFileName(filePath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Files that should not be modified by the cleaner.
    /// </summary>
    private static bool IsGeneratedFile(string filePath)
    {
        var normalized = filePath.Replace('\\', '/');
        if (normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase))
            return true;

        var fileName = Path.GetFileName(filePath);
        return fileName.Contains("AssemblyAttributes", StringComparison.OrdinalIgnoreCase)
            || fileName.Contains("AssemblyInfo", StringComparison.OrdinalIgnoreCase)
            || fileName.StartsWith("GlobalUsings", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// After file deletions/edits, gets fresh compilations from the updated solution
    /// and removes using directives for namespaces that no longer exist.
    /// Unlike CS8019-based cleanup, this works even when orphaned usings cause compilation errors
    /// (CS8019 is skipped for files with errors, but the orphaned using itself causes CS0246).
    /// </summary>
    internal static async Task<int> CleanupOrphanedNamespaceUsingsAsync(
        Solution updatedSolution, StreamWriter resultWriter)
    {
        Console.WriteLine($"[INFO] Checking for orphaned namespace usings...");
        var sw = System.Diagnostics.Stopwatch.StartNew();

        int cleanedFiles = 0, removedUsings = 0;

        foreach (var project in updatedSolution.Projects)
        {
            var compilation = await project.GetCompilationAsync();
            if (compilation == null) continue;

            foreach (var doc in project.Documents)
            {
                var docPath = doc.FilePath;
                if (string.IsNullOrEmpty(docPath) || IsGeneratedFile(docPath)
                    || AnalysisHelpers.IsIgnoredPath(docPath))
                    continue;

                var root = await doc.GetSyntaxRootAsync() as CompilationUnitSyntax;
                if (root == null || root.Usings.Count == 0) continue;

                var usingsToRemove = new List<UsingDirectiveSyntax>();
                foreach (var u in root.Usings)
                {
                    if (u.Alias != null) continue;
                    if (u.StaticKeyword.IsKind(SyntaxKind.StaticKeyword)) continue;

                    var ns = u.Name?.ToString().Trim();
                    if (string.IsNullOrEmpty(ns)) continue;

                    if (!IsNamespaceAccessible(ns, compilation))
                        usingsToRemove.Add(u);
                }

                if (usingsToRemove.Count == 0) continue;

                var newRoot = root.RemoveNodes(usingsToRemove, SyntaxRemoveOptions.KeepNoTrivia);
                if (newRoot == null) continue;

                await File.WriteAllTextAsync(docPath, newRoot.ToFullString());
                cleanedFiles++;
                removedUsings += usingsToRemove.Count;

                foreach (var u in usingsToRemove)
                {
                    var msg = $"[USING-CLEANUP] Removed orphaned 'using {u.Name};' from {Path.GetFileName(docPath)}";
                    Console.WriteLine(msg);
                    resultWriter.WriteLine(msg);
                }
            }
        }

        Console.WriteLine($"[INFO] Cleaned {removedUsings} orphaned namespace usings from {cleanedFiles} files in {sw.Elapsed.TotalSeconds:F1}s");
        return removedUsings;
    }

    /// <summary>
    /// Checks if a namespace is accessible from a compilation by walking GlobalNamespace.
    /// Used on fresh compilations (after file deletions) — no deletedFiles hack needed.
    /// </summary>
    private static bool IsNamespaceAccessible(string namespaceName, Compilation compilation)
    {
        var parts = namespaceName.Split('.');
        INamespaceSymbol? current = compilation.GlobalNamespace;
        foreach (var part in parts)
        {
            current = current.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
            if (current == null) return false;
        }
        return true;
    }

    /// <summary>
    /// Builds an updated Solution snapshot by removing deleted documents and
    /// replacing edited documents with their current text content.
    /// Used after auto-delete to produce a Solution whose compilations reflect
    /// the post-deletion state for namespace resolution.
    /// </summary>
    internal static Solution BuildUpdatedSolution(
        Solution solution,
        IReadOnlyCollection<string> deletedFiles,
        IReadOnlyDictionary<string, string> editedFiles)
    {
        var fileToDoc = new Dictionary<string, DocumentId>(StringComparer.OrdinalIgnoreCase);
        foreach (var project in solution.Projects)
            foreach (var doc in project.Documents)
                if (!string.IsNullOrEmpty(doc.FilePath))
                    fileToDoc.TryAdd(doc.FilePath, doc.Id);

        var updated = solution;

        foreach (var path in deletedFiles)
        {
            if (fileToDoc.TryGetValue(path, out var docId))
                updated = updated.RemoveDocument(docId);
            else
                Console.WriteLine($"[DEBUG] BuildUpdatedSolution: no DocumentId for deleted file {Path.GetFileName(path)}");
        }

        foreach (var (path, text) in editedFiles)
        {
            if (fileToDoc.TryGetValue(path, out var docId))
                updated = updated.WithDocumentText(docId, SourceText.From(text, System.Text.Encoding.UTF8));
            else
                Console.WriteLine($"[DEBUG] BuildUpdatedSolution: no DocumentId for edited file {Path.GetFileName(path)}");
        }

        Console.WriteLine($"[INFO] Updated solution snapshot: {deletedFiles.Count} removed, {editedFiles.Count} edited");
        return updated;
    }

    // Parallel PLINQ collection of CS8019/CS0105 spans.
    // Files with compilation errors are skipped — CS8019 is unreliable when types can't be resolved.
    private static HashSet<TextSpan> GetUnusedUsingSpans(this Compilation compilation)
    {
        return compilation.SyntaxTrees.AsParallel()
            .SelectMany(tree =>
            {
                var model = compilation.GetSemanticModel(tree);
                var diagnostics = model.GetDiagnostics();

                // If the file has any compilation errors, CS8019 may be a false positive
                if (diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
                    return [];

                return diagnostics
                    .Where(d => d.Id is "CS8019" or "CS0105")
                    .Select(d => d.Location.SourceSpan);
            })
            .ToHashSet();
    }
}
